Ihsanbara
digidevid/digidev-ui pull request #19
Opened 2021-11-18 13:01 UTC by ihsanbara94

added thank and confirmation component with responsive

2021-11-18 15:36 UTC, fshlarf commented on components/organisms/NavDoneTransaction.vue
> +<template>
file ini utk apa san?

2021-11-18 15:36 UTC, fshlarf commented on components/organisms/PortofolioAlumni.vue
> +        container
ini knp ditambah lg san? @ihsanbara94

2021-11-18 15:38 UTC, fshlarf requested changes
di file portofolio alumni, penambahan container gak perlu san

2021-11-19 04:27 UTC, ihsanbara94 commented on components/organisms/NavDoneTransaction.vue
> +<template>
page payment-page sama thankyou beda navbar nya shal,
jadi aku buat itu

2021-11-19 07:04 UTC, fshlarf approved these changes

2021-11-19 07:14 UTC, ibnuhazar101 commented on components/organisms/NavDoneTransaction.vue
> +<template>
cu, aku ada improve menu hamburger nya kemarin. coba liat component navigation line 3-7, line 241, 302, 308, 314.

2021-11-19 07:15 UTC, ibnuhazar101 commented on pages/payment-page/views/ClassOrdered.vue
> +    // price: {
kode ini masih perlu cu? kalo ga perlu lagi di hapus aja ya.

2021-11-19 07:18 UTC, ibnuhazar101 requested changes

2021-11-19 07:18 UTC, ibnuhazar101 commented on components/organisms/NavDoneTransaction.vue
> +<template>
> cu, aku ada improve menu hamburger nya kemarin. coba liat component navigation line 3-7, line 241, 302, 308, 314.

2021-11-19 07:32 UTC, ihsanbara94 commented on pages/payment-page/views/ClassOrdered.vue
> +    // price: {
kayaknya perlu nu, menampilkan class yg dipilih

2021-11-19 09:12 UTC, ibnuhazar101 approved these changes

2021-11-19 09:12 UTC, merged